name: Keyinsights workflow

on: 
  push:
    paths: 
      - 'Solutions/Skandisoft.KeyInsight/**'

env:
  FUNCTION_APP: func-keyinsight
  FUNCTION_APP_PATH: '.'    
  DOTNET_VERSION: '3.1.x'   

jobs: 
  build-test-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout master
        uses: actions/checkout@main
      - name: Setup dotnet v. ${{ env.DOTNET_VERSION }}
        uses: action/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build project
        shell: bash
        working-directory: ${{ env.FUNCTION_APP_PATH }}
        run: dotnet build --configuration Release --output ./output
      - name: Deploy function app
        uses: Azure/functions-action@v1
        with: 
          app-name: ${{ env.FUNCTION_APP }}
          package: ${{ env.FUNCTION_APP_PATH }}/output
          publish-profile:  ${{ secrets.AZURE_KEYINSIGHT_PUBLISH_PROFILE }}
